profile page
redacademy/msb-winter-2019 pull request #100
Opened 2019-03-21 21:41 UTC by kyltec

2019-03-21 23:00 UTC, siddharthparmar7 requested changes

2019-03-21 23:00 UTC, siddharthparmar7 commented on client/js/screens/Profile/styles.js
> +    width: 150,
use flexbox properties instead of giving fix height and width. use resize mode.

2019-03-22 20:18 UTC, kyltec commented
can you re-review this

2019-03-22 21:02 UTC, siddharthparmar7 approved these changes

2019-03-22 21:02 UTC, merged