Kt feature loader
redacademy/msb-winter-2019 pull request #59
Opened 2019-03-15 16:30 UTC by kyltec

2019-03-15 16:40 UTC, siddharthparmar7 requested changes
Please make the requested changes.

2019-03-15 16:40 UTC, siddharthparmar7 commented on client/js/components/Loader/styles.js
> +    marginTop: 300
you should not have this much margin. Please use flexbox properties instead.

2019-03-15 16:40 UTC, siddharthparmar7 commented on client/js/screens/Rewards/RewardsContainer.js
> +  }
if you are not creating a state then remove the constructor.

2019-03-15 16:40 UTC, siddharthparmar7 commented on client/js/screens/Rewards/RewardsContainer.js
> +    <Query
write a proper <Query> tag.

2019-03-15 18:52 UTC, kyltec commented
added asset files on this branch

2019-03-15 22:59 UTC, siddharthparmar7 requested changes

2019-03-15 22:59 UTC, siddharthparmar7 commented on client/js/components/Loader/Loader.js
> +  styles: PropTypes.object.isRequired
styles is not a prop. It a const that you imported from your styles.js file. Please remove proptypes if you do not have props to validate.

2019-03-15 22:59 UTC, siddharthparmar7 commented on client/js/screens/Card/CardContainer.js
>    constructor(props) {
If you do not have a state remove the constructor.

2019-03-18 17:16 UTC, siddharthparmar7 approved these changes

2019-03-18 17:16 UTC, merged