JY Create Beer Carousel
redacademy/msb-winter-2019 pull request #74
Opened 2019-03-19 18:59 UTC by jenjjy

2019-03-19 20:48 UTC, siddharthparmar7 requested changes

2019-03-19 20:48 UTC, siddharthparmar7 commented on client/js/components/Availability/styles.js
> +  container: {},
remove container.

2019-03-19 20:48 UTC, siddharthparmar7 commented on client/js/components/BeerCarousel/BeerCarousel.js
> +// }}
remove commented code.

2019-03-19 20:48 UTC, siddharthparmar7 commented on client/js/components/BeerCarousel/BeerCarousel.js
> +  _renderItem({ item, index }) {
if you are using _ for your methods then you should follow that convention for all your methods, throughout your project.

2019-03-19 20:48 UTC, siddharthparmar7 commented on client/js/components/BeerCarousel/BeerCarousel.js
> +  _renderItem({ item, index }) {
same as above.

2019-03-19 20:48 UTC, siddharthparmar7 commented on client/js/components/BeerCarousel/BeerCarousel.js
> +  _renderItemWithParallax({ item, index }, parallaxProps) {
same as above.

2019-03-19 20:48 UTC, siddharthparmar7 commented on client/js/components/BeerCarousel/BeerCarousel.js
> +  _renderLightItem({ item, index }) {
same as above

2019-03-19 20:48 UTC, siddharthparmar7 commented on client/js/components/BeerCarousel/BeerCarousel.js
> +  _renderDarkItem({ item, index }) {
same as above.

2019-03-19 20:48 UTC, siddharthparmar7 commented on client/js/components/BeerCarousel/BeerCarousel.js
> +  mainExample(number, title) {
looks like you copied this file from the docs and didn't remove unnecessary code. Please make the changes.

2019-03-19 20:48 UTC, siddharthparmar7 commented on client/js/components/BeerCarousel/BeerCarousel.js
> +        /> */}
remove unnecessary code and comments.

2019-03-19 20:48 UTC, siddharthparmar7 commented on client/js/screens/AllBeers/AllBeersContainer.js
>    constructor(props) {
remove the constructor if you are not creating a state.

2019-03-19 20:48 UTC, siddharthparmar7 commented on client/js/screens/AllBeers/AllBeersContainer.js
> +          console.log('ERROR:', error);
remove this console log.

2019-03-19 20:48 UTC, siddharthparmar7 commented on client/js/screens/Event/EventContainer.js
>    constructor(props) {
remove this constructor if you are not creating a state.

2019-03-20 19:10 UTC, jenjjy commented
Updated

2019-03-20 19:10 UTC, jenjjy commented
Start a new pull request with the noted changes

2019-03-20 19:10 UTC, closed without merging